const EMAIL_VERIFICATION_CONFIRMING_MIN_DURATION = 1.5
const EMAIL_VERIFICATION_CONFIRMED_DURATION = 0.9
const EMAIL_VERIFICATION_EXIT_DURATION = 0.28
const EMAIL_VERIFICATION_LOADING_REVEAL_DELAY = 0.4

export {
  EMAIL_VERIFICATION_CONFIRMING_MIN_DURATION,
  EMAIL_VERIFICATION_CONFIRMED_DURATION,
  EMAIL_VERIFICATION_EXIT_DURATION,
  EMAIL_VERIFICATION_LOADING_REVEAL_DELAY,
}
