const REGISTRATION_CONFIRMATION_LOADING_DURATION = 2.4
const REGISTRATION_CONFIRMATION_EXIT_DURATION = 0.28
const REGISTRATION_CONFIRMATION_STATUS_CHANGE_DELAY = 1.5

export {
  REGISTRATION_CONFIRMATION_EXIT_DURATION,
  REGISTRATION_CONFIRMATION_LOADING_DURATION,
  REGISTRATION_CONFIRMATION_STATUS_CHANGE_DELAY,
}
