const ACCESS_TOKEN_COOKIE_NAME = "capta_access_token"
const PENDING_VERIFICATION_EMAIL_COOKIE_NAME = "capta_pending_verification_email"
const PENDING_VERIFICATION_EMAIL_MAX_AGE_SECONDS = 15 * 60
const REFRESH_TOKEN_COOKIE_NAME = "capta_refresh_token"

export {
  ACCESS_TOKEN_COOKIE_NAME,
  PENDING_VERIFICATION_EMAIL_COOKIE_NAME,
  PENDING_VERIFICATION_EMAIL_MAX_AGE_SECONDS,
  REFRESH_TOKEN_COOKIE_NAME,
}
